general.import = [
  # "/Users/ktruesdell/.nvm/versions/node/v20.11.0/lib/node_modules/alacritty-themes/themes/Kitty.toml",
  # "~/.config/alacritty/alacritty-theme/themes/afterglow.toml"
  # "~/.config/alacritty/alacritty-theme/themes/alabaster_dark.toml"
  # "~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"
   "~/.config/alacritty/alacritty-theme/themes/hyper.toml"
  # "~/.config/alacritty/alacritty-theme/themes/terminal_app.toml"
  # "~/.config/alacritty/alacritty-theme/themes/chicago95.toml"
]

## NOTE: This produces a TON of messages at the botton and only way to dismiss them is to use the mouse and click the X box
general.live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"
decorations_theme_variant = "None"

opacity = 0.85
blur = true # false

  [window.padding]
  x = 0
  y = 0

[font]
size = 13


  [font.normal]
  family = "FiraMono Nerd Font"

# [colors.primary]
# foreground = "#ffffff"
# background = "#000000"

# [colors.normal]
# black = "#000000"

[bell]
animation = "Linear"

## NOTE: This does not work in alacritty - want to get this to work for vim keybindings
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "F"
mods = "Command|Control"
action = "ToggleFullscreen"

